#!/bin/bash

for f in *.pdf ; do
    echo $f;
    gs -dSAFER -dBATCH -dNOPAUSE -sDEVICE=png16m -r1200 -dTextAlphaBits=1 -dGraphicsAlphaBits=1 -sOutputFile=t.png $f
    # using AlphaBits=4 directly gives hairline cracks              
    convert -resize 25% t.png ${f%.pdf}.png
    rm t.png
done
