#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./run.sh

../../build/extract_aero_size --num --dmin 1e-9 --dmax 1e-7 --nbin 100 out/part_brown_free_df_3_0001
../../build/extract_sectional_aero_size --num out/sect_brown_free_df_3

../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_free_df_3_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_free_df_2_6_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_free_df_2_2_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_free_df_2_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_cont_df_3_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_cont_df_2_2_0001
../../build/test_fractal_self_preserve --dimless_vol_min 1e-3 --dimless_vol_max 10 --nbin 100 out/part_brown_cont_df_1_8_0001

../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/part_brown_free_df_3_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/restart/part_brown_free_df_3_0001
../../build/test_fractal_merge_files part_brown_free_df_3_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/part_brown_free_df_2_8_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/restart/part_brown_free_df_2_8_0001
../../build/test_fractal_merge_files part_brown_free_df_2_8_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/part_brown_free_df_2_4_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/restart/part_brown_free_df_2_4_0001
../../build/test_fractal_merge_files part_brown_free_df_2_4_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/part_brown_free_df_2_0001
../../build/test_fractal_dimless_time --free --n_init 1e14 out_dimless_t/restart/part_brown_free_df_2_0001
../../build/test_fractal_merge_files part_brown_free_df_2_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/part_brown_cont_df_3_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/restart/part_brown_cont_df_3_0001
../../build/test_fractal_merge_files part_brown_cont_df_3_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/part_brown_cont_df_1_8_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/restart/part_brown_cont_df_1_8_0001
../../build/test_fractal_merge_files part_brown_cont_df_1_8_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/part_brown_cont_df_1_0001
../../build/test_fractal_dimless_time --cont --n_init 1e14 out_dimless_t/restart/part_brown_cont_df_1_0001
../../build/test_fractal_merge_files part_brown_cont_df_1_0001

# Now run 'gnuplot -persist <filename>.gnuplot' to plot the data
