#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./run.sh

../../build/extract_aero_particles_kappa out/urban_plume_0001_00000001.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000002.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000003.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000004.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000005.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000006.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000007.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000008.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000009.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000010.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000011.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000012.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000013.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000014.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000015.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000016.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000017.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000018.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000019.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000020.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000021.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000022.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000023.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000024.nc
../../build/extract_aero_particles_kappa out/urban_plume_0001_00000025.nc

