#set(CMAKE_Fortran_FLAGS "-g -fimplicit-none -W -Wall -Wconversion -Wunderflow -Wimplicit-interface -Wno-unused -fbounds-check" CACHE STRING "")
set(NETCDF_INCLUDE_DIR "/Users/jcurtis2/Support/netcdf/include" CACHE STRING "")
set(NETCDF_C_LIB "/Users/jcurtis2/Support/netcdf/lib/libnetcdf.dylib" CACHE STRING "")
set(NETCDF_FORTRAN_LIB "/Users/jcurtis2/Support/netcdf/lib/libnetcdff.dylib" CACHE STRING "")
set(ENABLE_GSL ON CACHE BOOL "")
#set(ENABLE_C_SORT ON CACHE BOOL "")
set(ENABLE_MOSAIC ON CACHE BOOL "")
set(MOSAIC_INCLUDE_DIR "/Users/jcurtis2/subversion/mosaic/trunk/datamodules" CACHE STRING "")
set(MOSAIC_LIB "/Users/jcurtis2/subversion/mosaic/trunk/libmosaic.a" CACHE STRING "")
#set(ENABLE_SUNDIALS ON CACHE BOOL "")
#set(SUNDIALS_INCLUDE_DIR "/Users/mwest/opt/sundials-2.4.0/include" CACHE STRING "")
#set(SUNDIALS_NVECSERIAL_LIB "/Users/mwest/opt/sundials-2.4.0/lib/libsundials_nvecserial.a" CACHE STRING "")
#set(SUNDIALS_CVODE_LIB "/Users/mwest/opt/sundials-2.4.0/lib/libsundials_cvode.a" CACHE STRING "")
