set(CMAKE_Fortran_COMPILER "/sw/bin/mpif90" CACHE FILEPATH "")
set(CMAKE_C_FLAGS "-arch i386" CACHE STRING "")
set(ENABLE_MPI ON CACHE BOOL "")
set(ENABLE_MOSAIC ON CACHE BOOL "")
set(ENABLE_SUNDIALS ON CACHE BOOL "")
set(NETCDF_C_LIB "/sw/lib/libnetcdf.3.dylib" CACHE STRING "")
set(SUNDIALS_INCLUDE_DIR "/Users/mwest/opt/sundials-2.4.0/include" CACHE STRING "")
set(SUNDIALS_NVECSERIAL_LIB "/Users/mwest/opt/sundials-2.4.0/lib/libsundials_nvecserial.a" CACHE STRING "")
set(SUNDIALS_CVODE_LIB "/Users/mwest/opt/sundials-2.4.0/lib/libsundials_cvode.a" CACHE STRING "")
