#!/bin/sh

echo "pbs/run_urban_plume_central_dist_00.pbs"
qsub pbs/run_urban_plume_central_dist_00.pbs
echo "pbs/run_urban_plume_central_dist_01.pbs"
qsub pbs/run_urban_plume_central_dist_01.pbs
echo "pbs/run_urban_plume_central_dist_02.pbs"
qsub pbs/run_urban_plume_central_dist_02.pbs
echo "pbs/run_urban_plume_central_dist_04.pbs"
qsub pbs/run_urban_plume_central_dist_04.pbs
echo "pbs/run_urban_plume_central_dist_06.pbs"
qsub pbs/run_urban_plume_central_dist_06.pbs
echo "pbs/run_urban_plume_central_dist_08.pbs"
qsub pbs/run_urban_plume_central_dist_08.pbs
echo "pbs/run_urban_plume_central_dist_12.pbs"
qsub pbs/run_urban_plume_central_dist_12.pbs
echo "pbs/run_urban_plume_central_dist_16.pbs"
qsub pbs/run_urban_plume_central_dist_16.pbs
echo "pbs/run_urban_plume_collect_dist_00.pbs"
qsub pbs/run_urban_plume_collect_dist_00.pbs
echo "pbs/run_urban_plume_collect_dist_01.pbs"
qsub pbs/run_urban_plume_collect_dist_01.pbs
echo "pbs/run_urban_plume_collect_dist_02.pbs"
qsub pbs/run_urban_plume_collect_dist_02.pbs
echo "pbs/run_urban_plume_collect_dist_04.pbs"
qsub pbs/run_urban_plume_collect_dist_04.pbs
echo "pbs/run_urban_plume_collect_dist_06.pbs"
qsub pbs/run_urban_plume_collect_dist_06.pbs
echo "pbs/run_urban_plume_collect_dist_08.pbs"
qsub pbs/run_urban_plume_collect_dist_08.pbs
echo "pbs/run_urban_plume_collect_dist_12.pbs"
qsub pbs/run_urban_plume_collect_dist_12.pbs
echo "pbs/run_urban_plume_collect_dist_16.pbs"
qsub pbs/run_urban_plume_collect_dist_16.pbs
echo "pbs/run_urban_plume_dist_central_00.pbs"
qsub pbs/run_urban_plume_dist_central_00.pbs
echo "pbs/run_urban_plume_dist_central_01.pbs"
qsub pbs/run_urban_plume_dist_central_01.pbs
echo "pbs/run_urban_plume_dist_central_02.pbs"
qsub pbs/run_urban_plume_dist_central_02.pbs
echo "pbs/run_urban_plume_dist_central_04.pbs"
qsub pbs/run_urban_plume_dist_central_04.pbs
echo "pbs/run_urban_plume_dist_central_06.pbs"
qsub pbs/run_urban_plume_dist_central_06.pbs
echo "pbs/run_urban_plume_dist_central_08.pbs"
qsub pbs/run_urban_plume_dist_central_08.pbs
echo "pbs/run_urban_plume_dist_central_12.pbs"
qsub pbs/run_urban_plume_dist_central_12.pbs
echo "pbs/run_urban_plume_dist_central_16.pbs"
qsub pbs/run_urban_plume_dist_central_16.pbs
echo "pbs/run_urban_plume_dist_dist_00.pbs"
qsub pbs/run_urban_plume_dist_dist_00.pbs
echo "pbs/run_urban_plume_dist_dist_01.pbs"
qsub pbs/run_urban_plume_dist_dist_01.pbs
echo "pbs/run_urban_plume_dist_dist_02.pbs"
qsub pbs/run_urban_plume_dist_dist_02.pbs
echo "pbs/run_urban_plume_dist_dist_04.pbs"
qsub pbs/run_urban_plume_dist_dist_04.pbs
echo "pbs/run_urban_plume_dist_dist_06.pbs"
qsub pbs/run_urban_plume_dist_dist_06.pbs
echo "pbs/run_urban_plume_dist_dist_08.pbs"
qsub pbs/run_urban_plume_dist_dist_08.pbs
echo "pbs/run_urban_plume_dist_dist_12.pbs"
qsub pbs/run_urban_plume_dist_dist_12.pbs
echo "pbs/run_urban_plume_dist_dist_16.pbs"
qsub pbs/run_urban_plume_dist_dist_16.pbs
echo "pbs/run_urban_plume_dist_none_00.pbs"
qsub pbs/run_urban_plume_dist_none_00.pbs
echo "pbs/run_urban_plume_dist_none_01.pbs"
qsub pbs/run_urban_plume_dist_none_01.pbs
echo "pbs/run_urban_plume_dist_none_02.pbs"
qsub pbs/run_urban_plume_dist_none_02.pbs
echo "pbs/run_urban_plume_dist_none_04.pbs"
qsub pbs/run_urban_plume_dist_none_04.pbs
echo "pbs/run_urban_plume_dist_none_06.pbs"
qsub pbs/run_urban_plume_dist_none_06.pbs
echo "pbs/run_urban_plume_dist_none_08.pbs"
qsub pbs/run_urban_plume_dist_none_08.pbs
echo "pbs/run_urban_plume_dist_none_12.pbs"
qsub pbs/run_urban_plume_dist_none_12.pbs
echo "pbs/run_urban_plume_dist_none_16.pbs"
qsub pbs/run_urban_plume_dist_none_16.pbs
echo "pbs/run_urban_plume_dist_single_00.pbs"
qsub pbs/run_urban_plume_dist_single_00.pbs
echo "pbs/run_urban_plume_dist_single_01.pbs"
qsub pbs/run_urban_plume_dist_single_01.pbs
echo "pbs/run_urban_plume_dist_single_02.pbs"
qsub pbs/run_urban_plume_dist_single_02.pbs
echo "pbs/run_urban_plume_dist_single_04.pbs"
qsub pbs/run_urban_plume_dist_single_04.pbs
echo "pbs/run_urban_plume_dist_single_06.pbs"
qsub pbs/run_urban_plume_dist_single_06.pbs
echo "pbs/run_urban_plume_dist_single_08.pbs"
qsub pbs/run_urban_plume_dist_single_08.pbs
echo "pbs/run_urban_plume_dist_single_12.pbs"
qsub pbs/run_urban_plume_dist_single_12.pbs
echo "pbs/run_urban_plume_dist_single_16.pbs"
qsub pbs/run_urban_plume_dist_single_16.pbs
echo "pbs/run_urban_plume_local1_dist_00.pbs"
qsub pbs/run_urban_plume_local1_dist_00.pbs
echo "pbs/run_urban_plume_local1_dist_01.pbs"
qsub pbs/run_urban_plume_local1_dist_01.pbs
echo "pbs/run_urban_plume_local1_dist_02.pbs"
qsub pbs/run_urban_plume_local1_dist_02.pbs
echo "pbs/run_urban_plume_local1_dist_04.pbs"
qsub pbs/run_urban_plume_local1_dist_04.pbs
echo "pbs/run_urban_plume_local1_dist_06.pbs"
qsub pbs/run_urban_plume_local1_dist_06.pbs
echo "pbs/run_urban_plume_local1_dist_08.pbs"
qsub pbs/run_urban_plume_local1_dist_08.pbs
echo "pbs/run_urban_plume_local1_dist_12.pbs"
qsub pbs/run_urban_plume_local1_dist_12.pbs
echo "pbs/run_urban_plume_local1_dist_16.pbs"
qsub pbs/run_urban_plume_local1_dist_16.pbs
echo "pbs/run_urban_plume_local2_dist_00.pbs"
qsub pbs/run_urban_plume_local2_dist_00.pbs
echo "pbs/run_urban_plume_local2_dist_01.pbs"
qsub pbs/run_urban_plume_local2_dist_01.pbs
echo "pbs/run_urban_plume_local2_dist_02.pbs"
qsub pbs/run_urban_plume_local2_dist_02.pbs
echo "pbs/run_urban_plume_local2_dist_04.pbs"
qsub pbs/run_urban_plume_local2_dist_04.pbs
echo "pbs/run_urban_plume_local2_dist_06.pbs"
qsub pbs/run_urban_plume_local2_dist_06.pbs
echo "pbs/run_urban_plume_local2_dist_08.pbs"
qsub pbs/run_urban_plume_local2_dist_08.pbs
echo "pbs/run_urban_plume_local2_dist_12.pbs"
qsub pbs/run_urban_plume_local2_dist_12.pbs
echo "pbs/run_urban_plume_local2_dist_16.pbs"
qsub pbs/run_urban_plume_local2_dist_16.pbs
echo "pbs/run_urban_plume_local3_dist_00.pbs"
qsub pbs/run_urban_plume_local3_dist_00.pbs
echo "pbs/run_urban_plume_local3_dist_01.pbs"
qsub pbs/run_urban_plume_local3_dist_01.pbs
echo "pbs/run_urban_plume_local3_dist_02.pbs"
qsub pbs/run_urban_plume_local3_dist_02.pbs
echo "pbs/run_urban_plume_local3_dist_04.pbs"
qsub pbs/run_urban_plume_local3_dist_04.pbs
echo "pbs/run_urban_plume_local3_dist_06.pbs"
qsub pbs/run_urban_plume_local3_dist_06.pbs
echo "pbs/run_urban_plume_local3_dist_08.pbs"
qsub pbs/run_urban_plume_local3_dist_08.pbs
echo "pbs/run_urban_plume_local3_dist_12.pbs"
qsub pbs/run_urban_plume_local3_dist_12.pbs
echo "pbs/run_urban_plume_local3_dist_16.pbs"
qsub pbs/run_urban_plume_local3_dist_16.pbs
