#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./1_run_sect.sh

../../build/extract_sectional_aero_time out/drydep_sect
../../build/extract_sectional_aero_size --num out/drydep_sect
../../build/extract_sectional_aero_size --mass out/drydep_sect
