#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./1_run_dry_dep_modal.sh

../../build/drydep_modal_process out/modal_dpg_00001000000000000000_sig_2_5_emerson_grass
