#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./1_run.sh

../../build/ogo_test_process

../../build/extract_env out/ogo_test_0001
../../build/extract_gas out/ogo_test_0001
../../build/extract_aero_time out/ogo_test_0001
../../build/extract_aero_size --num --dmin 1e-9 --dmax 1e-5 --nbin 100 out/ogo_test_0001
../../build/extract_aero_size --mass --dmin 1e-9 --dmax 1e-5 --nbin 100 out/ogo_test_0001

../../build/extract_aero_particles out/ogo_test_0001_00000001.nc
../../build/extract_aero_particles out/ogo_test_0001_00000012.nc
../../build/extract_aero_particles out/ogo_test_0001_00000030.nc
../../build/extract_aero_particles out/ogo_test_0001_00000054.nc
../../build/extract_aero_particles out/ogo_test_0001_00000073.nc

# Now run ./3_plot.sh to plot the data
