#!/bin/sh

# exit on error
set -e
# turn on command echoing
set -v

# The data should have already been generated by ./run.sh

../../build/chamber_process

# Now run 'gnuplot -persist <filename>.gnuplot' to plot the data
