! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Auxiliary Routines File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cb05cl_ae5_Util.f90
! Time                 : Thu Feb  8 11:36:55 2018
! Working directory    : /home/Earth/mdawson/Documents/partmc-chem/partmc/test/chemistry/cb05cl_ae5
! Equation file        : cb05cl_ae5.kpp
! Output root filename : cb05cl_ae5
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cb05cl_ae5_Util

  USE cb05cl_ae5_Parameters
  IMPLICIT NONE

CONTAINS



! User INLINED Utility Functions


! ****************************************************************
!                            
! InitSaveData - Opens the data file for writing
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE NewInitSaveData(counter, nsteps)

        USE model_Parameters, ONLY : NREACT, NVAR
        USE model_monitor, ONLY : SPC_NAMES, EQN_NAMES
        USE model_GLOBAL, only : ncconcid, ncrateid, ncirrid, JDAY, &
                        ncconcids, ncrateids, ncirrids
        USE netcdf, ONLY : NF90_CREATE, NF90_DEF_DIM, NF90_PUT_ATT, &
                        NF90_UNLIMITED, NF90_CLASSIC_MODEL, NF90_NETCDF4, &
                        NF90_SHARE, NF90_GLOBAL, NF90_ENDDEF
  
        Integer counter, length, ierr, i, dimid, status, nsteps
        character*200 filename
        character*200 eqnname, filename1
        write(filename1,'(i4)') counter

        filename='MECHANISM_Spec_'//TRIM(ADJUSTL(filename1))//'.nc'
        
        call checknc(nf90_create(filename, NF90_CLASSIC_MODEL, ncconcid))
        call checknc(nf90_def_dim(ncconcid, 'SIM', NF90_UNLIMITED, dimid))
        call checknc(nf90_def_dim(ncconcid, 'TSTEP', nsteps, dimid))
        call checknc(nf90_def_dim(ncconcid, 'DATE-TIME', 2, dimid))
        call checknc(nf90_def_dim(ncconcid, 'VAR', 1, dimid))
        call checknc(nf90_put_att(ncconcid, nf90_GLOBAL, 'MECH', 'MECHANISM'))
        call checknc(nf90_put_att(ncconcid, nf90_GLOBAL, 'SDATE', JDAY))
        
        call AddStdVar(ncconcid)

        DO i = 1, NVAR
            call AddVarWithUnitDesc(ncconcid, TRIM(SPC_NAMES(i)), 'ppm', &
              TRIM(SPC_NAMES(i))//' in micromoles per mole of air', ncconcids(i)1.5E-12,0.0E+00,0.0E+00,0.6,1.0)
        ENDDO
        call checknc(nf90_enddef(ncconcid))

        filename='MECHANISM_Rate_'//TRIM(ADJUSTL(filename1))//'.nc'

        call checknc(nf90_create(filename, NF90_CLASSIC_MODEL, ncrateid))
        call checknc(nf90_def_dim(ncrateid, 'SIM', NF90_UNLIMITED, dimid))
        call checknc(nf90_def_dim(ncrateid, 'TSTEP', nsteps, dimid))
        call checknc(nf90_def_dim(ncrateid, 'DATE-TIME', 2, dimid))
        call checknc(nf90_def_dim(ncrateid, 'VAR', 1, dimid))
        call checknc(nf90_put_att(ncrateid, nf90_GLOBAL, 'MECH', 'MECHANISM'))
        call checknc(nf90_put_att(ncrateid, nf90_GLOBAL, 'SDATE', JDAY))
        
        call AddStdVar(ncrateid)
        
        DO i = 1, NREACT
            write(eqnname,'(i4)') I
            eqnname = 'RXN_'//TRIM(ADJUSTL(eqnname))
            call AddVarWithUnitDesc(ncrateid, TRIM(eqnname), 'molecules * cm**-31.5E-12,0.0E+00,0.0E+00,0.6,1.0)
              TRIM(EQN_NAMES(i))//' in molecules per cubic centimenter', ncratei1.5E-12,0.0E+00,0.0E+00,0.6,1.0)
        ENDDO
        call checknc(nf90_enddef(ncrateid))

        filename='MECHANISM_IRR_'//TRIM(ADJUSTL(filename1))//'.nc'

        call checknc(nf90_create(filename, NF90_CLASSIC_MODEL, ncirrid))
        call checknc(nf90_def_dim(ncirrid, 'SIM', NF90_UNLIMITED, dimid))
        call checknc(nf90_def_dim(ncirrid, 'TSTEP', nsteps, dimid))
        call checknc(nf90_def_dim(ncirrid, 'DATE-TIME', 2, dimid))
        call checknc(nf90_def_dim(ncirrid, 'VAR', 1, dimid))
        call checknc(nf90_put_att(ncirrid, nf90_GLOBAL, 'MECH', 'MECHANISM'))
        call checknc(nf90_put_att(ncirrid, nf90_GLOBAL, 'SDATE', JDAY))
        
        call AddStdVar(ncirrid)
        
        DO i = 1, NREACT
            write(eqnname,'(i4)') I
            eqnname = 'IRR_'//TRIM(ADJUSTL(eqnname))
            call AddVarWithUnitDesc(ncirrid, TRIM(eqnname), 'ppm', &
              TRIM(EQN_NAMES(i))//' in micromoles per mole of air', ncirrids(i))1.5E-12,0.0E+00,0.0E+00,0.6,1.0)
        ENDDO
        call checknc(nf90_enddef(ncirrid))
      END SUBROUTINE NewInitSaveData

      SUBROUTINE checknc(status)
        use netcdf
        integer, intent(in) :: status
        
        if(status /= nf90_noerr) then
          print *, trim(nf90_strerror(status))
          stop 2
        end if
      END SUBROUTINE checknc

      SUBROUTINE AddStdVar(ncid)
        use model_Global, ONLY : ncstdids, ncconcid, ncirrid
        
        integer, intent(in) :: ncid
        integer i
        i = 1
        call AddVarWithUnitDesc(ncid, 'TIME', 'seconds from start', &
          'seconds from starting time (global variable SDATE)', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'TFLAG', '<YYYYJJJ, HHMMSS>', &
          'Julian data and time', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'LAT', 'decimal degrees east', &
          'Latitude in degrees east', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'LON', 'decimal degrees north', &
          'Longitude in degrees west', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'PRESS', 'hPa', &
          'Pressure in hecta Pascals', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'TEMP', 'K', &
          'Temperature in degrees Kelvin', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'THETA', 'decimal degrees', &
          'Solar zenith angle in decimal degrees', ncstdids(i))
        i = i + 1
        call AddVarWithUnitDesc(ncid, 'CFACTOR', 'Mmolecules**1 * cm**-3', &
          'Air in micromoles per mole of air', ncstdids(i))
        if (ncid .eq. ncconcid .or. ncid .eq. ncirrid) then
            i = i + 1
            call AddVarWithUnitDesc(ncid, 'H2O', 'ppm', &
              'Water in micromoles per mole of air', ncstdids(i))
            i = i + 1
            call AddVarWithUnitDesc(ncid, 'RO2', 'ppm', &
              'Peroxy radicals in micromoles per mole of air', ncstdids(i))
        else
            i = i + 1
            call AddVarWithUnitDesc(ncid, 'H2O', 'molecules * cm**-3', &
              'Water in molecules per cubic centimeter', ncstdids(i))
            i = i + 1
            call AddVarWithUnitDesc(ncid, 'RO2', 'molecules * cm**-3', &
              'Peroxy radicals in molecules per cubic centimeter', ncstdids(i))
        endif
      END SUBROUTINE AddStdVar

      SUBROUTINE AddVarWithUnitDesc(ncid, varname, unit, desc, varid)
        use netcdf, only : nf90_inq_dimid, nf90_inquire_dimension, &
                           nf90_def_var, nf90_put_att, nf90_double, nf90_int
        integer, intent(out) :: varid
        integer ncid, dimid0, dimid1, status, dimid2, dimid3, templen
        character(*) varname, unit, desc
        character(20) tempname
        call checknc(nf90_inq_dimid(ncid, 'SIM', dimid0))
        call checknc(nf90_inq_dimid(ncid, 'TSTEP', dimid1))
        if (trim(varname) .eq. 'TFLAG') then
            call checknc(nf90_inq_dimid(ncid, 'VAR', dimid2))
            call checknc(nf90_inquire_dimension(ncid, dimid2, tempname, templen)1.5E-12,0.0E+00,0.0E+00,0.6,1.0)
            call checknc(nf90_inq_dimid(ncid, 'DATE-TIME', dimid3))
            call checknc(nf90_def_var(ncid, TRIM(varname), nf90_int, &
               (/ dimid3, dimid2, dimid1, dimid0 /), varid))
        else
            call checknc(nf90_def_var(ncid, TRIM(varname), nf90_double, &
               (/ dimid1, dimid0 /), varid))
        ENDIF
        call checknc(nf90_put_att(ncid, varid, 'units', trim(unit)))
        call checknc(nf90_put_att(ncid, varid, 'var_desc', desc))
        call checknc(nf90_put_att(ncid, varid, 'long_name', varname))
      END SUBROUTINE AddVarWithUnitDesc

! End of InitSaveData function
! ****************************************************************
! ****************************************************************
!                            
! SaveData - Write LOOKAT species in the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE NewSaveData(counter)
        integer counter
        call WriteConc(counter)
        call WriteRate(counter)
        call WriteIrr(counter)
      END SUBROUTINE NewSaveData
      
      SUBROUTINE WriteConc(counter)
        use model_Parameters, ONLY : NVAR
        !use model_Monitor
        use model_Global, ONLY : ncconcid, ncconcids, C

        integer counter
        
        call WriteBoth(ncconcid, counter)
        call AddThisHour(ncconcid, ncconcids, C, NVAR, counter)
      END SUBROUTINE WriteConc

      SUBROUTINE WriteRate(counter)
        use model_Parameters, ONLY : NREACT
        !use model_Monitor
        use model_Global, ONLY : ncrateid, ncrateids, RCONST
        
        integer i, counter
        
        call WriteBoth(ncrateid, counter)
        call AddThisHour(ncrateid, ncrateids, RCONST, NREACT, counter)
      END SUBROUTINE WriteRate

      SUBROUTINE WriteIrr(counter)
        use model_Parameters, ONLY : NREACT
        !use model_Monitor
        use model_Global, ONLY : ncirrid, ncirrids, IRR
        
        integer i, counter
        
        call WriteBoth(ncirrid, counter)
        call AddThisHour(ncirrid, ncirrids, IRR, NREACT, counter)
        do i = 1, NREACT
            IRR(i) = 0.
        enddo
      END SUBROUTINE WriteIrr

      SUBROUTINE WriteBoth(ncid, counter)
        use model_Global, ONLY : ncstdids,TIME,LAT,LON,PRESS,TEMP,THETA,&
            CFACTOR,RO2,H2O,intcount,JDATE,ncconcid, ncirrid
        use netcdf, ONLY : nf90_inq_dimid, nf90_inquire_dimension, nf90_put_var
        
        integer, intent(in) :: ncid, counter
        integer i, j, dimid, dim, add_days, OUT_JDATE
        character*100 name
        integer, dimension(2) :: start
        integer tflag
        
        start = (/ intcount, counter /)

        i = 1
        call checknc(nf90_put_var(ncid, ncstdids(i), TIME, start))
        i = i + 1

        call checknc(nf90_inq_dimid(ncid, 'VAR', dimid))
        call checknc(nf90_inquire_dimension(ncid, dimid, name, dim))
        add_days = int(TIME)/3600/24
        OUT_JDATE = JDATE + add_days
        TFLAG = mod(int(time), 24*3600)
        TFLAG = TFLAG/3600 * 10000
        TFLAG = TFLAG + mod(int(TIME), 3600) / 60 * 100
        TFLAG = TFLAG + mod(int(TIME), 60)
        call checknc(nf90_put_var(ncid, ncstdids(i), &
          reshape((/(OUT_JDATE, j = 1, dim)/), shape = (/1, dim, 1, 1/)), &
          start = (/1, 1, intcount, counter/), stride = (/2, 1, 1, 1/)))
        call checknc(nf90_put_var(ncid, ncstdids(i), &
          reshape((/(TFLAG, j = 1, dim)/), shape = (/1, dim, 1, 1/)), &
          start = (/2, 1, intcount, counter/), stride = (/2, 1, 1, 1/)))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), LAT, start))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), LON, start))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), PRESS, start))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), TEMP, start))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), THETA, start))
        i = i + 1
        call checknc(nf90_put_var(ncid, ncstdids(i), CFACTOR, start))
        if (ncid .eq. ncconcid .or. ncid .eq. ncirrid) then
            i = i + 1
            call checknc(nf90_put_var(ncid, ncstdids(i), H2O/CFACTOR, start))
            i = i + 1
            call checknc(nf90_put_var(ncid, ncstdids(i), RO2/CFACTOR, start))
        else
            i = i + 1
            call checknc(nf90_put_var(ncid, ncstdids(i), H2O, start))
            i = i + 1
            call checknc(nf90_put_var(ncid, ncstdids(i), RO2, start))
        endif
      END SUBROUTINE WriteBoth
      
      SUBROUTINE AddThisHour(ncid, ncids, values, nvalues, counter)
        use model_Global, ONLY : ncconcid, ncirrid, CFACTOR, intcount
        use netcdf, ONLY : nf90_put_var
        
        integer, intent(in) :: ncid, nvalues, counter
        integer, intent(in), dimension(nvalues) :: ncids
        real(kind=dp), dimension(nvalues), intent(in) :: values
        real(kind=dp) value
        integer i
        
        integer, dimension(2) :: start
        start = (/ intcount, counter/)

        do i = 1, nvalues
            value = values(i)
            if (ncid .eq. ncconcid .or. ncid .eq. ncirrid) then
                value = value / CFACTOR
            endif
            call checknc(nf90_put_var(ncid, ncids(i), value, start))
        enddo
      END SUBROUTINE AddThisHour

! End of SaveData function
! ****************************************************************

! ****************************************************************
!                            
! CloseSaveData - Close the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE NewSyncData ()
          USE model_Global, ONLY : ncconcid, ncrateid, ncirrid
          use netcdf, ONLY : nf90_sync
          
          call checknc(nf90_sync(ncconcid))
          call checknc(nf90_sync(ncrateid))
          call checknc(nf90_sync(ncirrid))

      END SUBROUTINE NewSyncData

      SUBROUTINE NewCloseData ()
          USE model_Global, ONLY : ncconcid, ncrateid, ncirrid
          use netcdf, ONLY : nf90_close

          call checknc(nf90_close(ncconcid))
          call checknc(nf90_close(ncrateid))
          call checknc(nf90_close(ncirrid))

      END SUBROUTINE NewCloseData

! End of CloseSaveData function
! ****************************************************************
         

! End INLINED Utility Functions

! Utility Functions from KPP_HOME/util/util
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! UTIL - Utility functions
!   Arguments :
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! ****************************************************************
!                            
! InitSaveData - Opens the data file for writing
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE InitSaveData ()

      USE cb05cl_ae5_Parameters

      open(10, file='cb05cl_ae5.dat')

      END SUBROUTINE InitSaveData

! End of InitSaveData function
! ****************************************************************

! ****************************************************************
!                            
! SaveData - Write LOOKAT species in the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE SaveData ()

      USE cb05cl_ae5_Global
      USE cb05cl_ae5_Monitor

      INTEGER i

      WRITE(10,999) (TIME-TSTART)/3600.D0,  &
                   (C(LOOKAT(i))/CFACTOR, i=1,NLOOKAT)
999   FORMAT(E24.16,100(1X,E24.16))

      END SUBROUTINE SaveData

! End of SaveData function
! ****************************************************************

! ****************************************************************
!                            
! CloseSaveData - Close the data file 
!   Parameters :                                                  
!
! ****************************************************************

      SUBROUTINE CloseSaveData ()

      USE cb05cl_ae5_Parameters

      CLOSE(10)

      END SUBROUTINE CloseSaveData

! End of CloseSaveData function
! ****************************************************************

! ****************************************************************
!                            
! GenerateMatlab - Generates MATLAB file to load the data file 
!   Parameters : 
!                It will have a character string to prefix each 
!                species name with.                                                 
!
! ****************************************************************

      SUBROUTINE GenerateMatlab ( PREFIX )

      USE cb05cl_ae5_Parameters
      USE cb05cl_ae5_Global
      USE cb05cl_ae5_Monitor

      
      CHARACTER(LEN=8) PREFIX 
      INTEGER i

      open(20, file='cb05cl_ae5.m')
      write(20,*) 'load cb05cl_ae5.dat;'
      write(20,990) PREFIX
990   FORMAT(A1,'c = cb05cl_ae5;')
      write(20,*) 'clear cb05cl_ae5;'
      write(20,991) PREFIX, PREFIX
991   FORMAT(A1,'t=',A1,'c(:,1);')
      write(20,992) PREFIX
992   FORMAT(A1,'c(:,1)=[];')

      do i=1,NLOOKAT
        write(20,993) PREFIX, SPC_NAMES(LOOKAT(i)), PREFIX, i
993     FORMAT(A1,A6,' = ',A1,'c(:,',I2,');')
      end do
      
      CLOSE(20)

      END SUBROUTINE GenerateMatlab

! End of GenerateMatlab function
! ****************************************************************


! End Utility Functions from KPP_HOME/util/util
! End of UTIL function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_user2kpp - function to copy concentrations from USER to KPP
!   Arguments :
!      V_USER    - Concentration of variable species in USER's order
!      V         - Concentrations of variable species (local)
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_user2kpp ( V_USER, V )

! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)
! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)

  V(34) = V_USER(1)
  V(60) = V_USER(2)
  V(59) = V_USER(3)
  V(4) = V_USER(4)
  V(3) = V_USER(5)
  V(1) = V_USER(6)
  V(2) = V_USER(7)
  V(66) = V_USER(8)
  V(26) = V_USER(9)
  V(67) = V_USER(10)
  V(18) = V_USER(11)
  V(42) = V_USER(12)
  V(47) = V_USER(13)
  V(50) = V_USER(14)
  V(43) = V_USER(15)
  V(72) = V_USER(16)
  V(51) = V_USER(17)
  V(35) = V_USER(18)
  V(37) = V_USER(19)
  V(29) = V_USER(20)
  V(44) = V_USER(21)
  V(61) = V_USER(22)
  V(28) = V_USER(23)
  V(38) = V_USER(24)
  V(39) = V_USER(25)
  V(46) = V_USER(26)
  V(69) = V_USER(27)
  V(21) = V_USER(28)
  V(27) = V_USER(29)
  V(53) = V_USER(30)
  V(57) = V_USER(31)
  V(5) = V_USER(32)
  V(58) = V_USER(33)
  V(64) = V_USER(34)
  V(36) = V_USER(35)
  V(45) = V_USER(36)
  V(41) = V_USER(37)
  V(24) = V_USER(38)
  V(68) = V_USER(39)
  V(74) = V_USER(40)
  V(70) = V_USER(41)
  V(62) = V_USER(42)
  V(73) = V_USER(43)
  V(20) = V_USER(44)
  V(63) = V_USER(45)
  V(71) = V_USER(46)
  V(54) = V_USER(47)
  V(48) = V_USER(48)
  V(30) = V_USER(49)
  V(22) = V_USER(50)
  V(31) = V_USER(51)
  V(56) = V_USER(52)
  V(32) = V_USER(53)
  V(40) = V_USER(54)
  V(49) = V_USER(55)
  V(7) = V_USER(56)
  V(6) = V_USER(57)
  V(19) = V_USER(58)
  V(8) = V_USER(59)
  V(9) = V_USER(60)
  V(52) = V_USER(61)
  V(33) = V_USER(62)
  V(23) = V_USER(63)
  V(10) = V_USER(64)
  V(11) = V_USER(65)
  V(12) = V_USER(66)
  V(13) = V_USER(67)
  V(65) = V_USER(68)
  V(55) = V_USER(69)
  V(25) = V_USER(70)
  V(14) = V_USER(71)
  V(15) = V_USER(72)
  V(16) = V_USER(73)
      
END SUBROUTINE Shuffle_user2kpp

! End of Shuffle_user2kpp function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Shuffle_kpp2user - function to restore concentrations from KPP to USER
!   Arguments :
!      V         - Concentrations of variable species (local)
!      V_USER    - Concentration of variable species in USER's order
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Shuffle_kpp2user ( V, V_USER )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! V_USER - Concentration of variable species in USER's order
  REAL(kind=dp) :: V_USER(NVAR)

  V_USER(1) = V(34)
  V_USER(2) = V(60)
  V_USER(3) = V(59)
  V_USER(4) = V(4)
  V_USER(5) = V(3)
  V_USER(6) = V(1)
  V_USER(7) = V(2)
  V_USER(8) = V(66)
  V_USER(9) = V(26)
  V_USER(10) = V(67)
  V_USER(11) = V(18)
  V_USER(12) = V(42)
  V_USER(13) = V(47)
  V_USER(14) = V(50)
  V_USER(15) = V(43)
  V_USER(16) = V(72)
  V_USER(17) = V(51)
  V_USER(18) = V(35)
  V_USER(19) = V(37)
  V_USER(20) = V(29)
  V_USER(21) = V(44)
  V_USER(22) = V(61)
  V_USER(23) = V(28)
  V_USER(24) = V(38)
  V_USER(25) = V(39)
  V_USER(26) = V(46)
  V_USER(27) = V(69)
  V_USER(28) = V(21)
  V_USER(29) = V(27)
  V_USER(30) = V(53)
  V_USER(31) = V(57)
  V_USER(32) = V(5)
  V_USER(33) = V(58)
  V_USER(34) = V(64)
  V_USER(35) = V(36)
  V_USER(36) = V(45)
  V_USER(37) = V(41)
  V_USER(38) = V(24)
  V_USER(39) = V(68)
  V_USER(40) = V(74)
  V_USER(41) = V(70)
  V_USER(42) = V(62)
  V_USER(43) = V(73)
  V_USER(44) = V(20)
  V_USER(45) = V(63)
  V_USER(46) = V(71)
  V_USER(47) = V(54)
  V_USER(48) = V(48)
  V_USER(49) = V(30)
  V_USER(50) = V(22)
  V_USER(51) = V(31)
  V_USER(52) = V(56)
  V_USER(53) = V(32)
  V_USER(54) = V(40)
  V_USER(55) = V(49)
  V_USER(56) = V(7)
  V_USER(57) = V(6)
  V_USER(58) = V(19)
  V_USER(59) = V(8)
  V_USER(60) = V(9)
  V_USER(61) = V(52)
  V_USER(62) = V(33)
  V_USER(63) = V(23)
  V_USER(64) = V(10)
  V_USER(65) = V(11)
  V_USER(66) = V(12)
  V_USER(67) = V(13)
  V_USER(68) = V(65)
  V_USER(69) = V(55)
  V_USER(70) = V(25)
  V_USER(71) = V(14)
  V_USER(72) = V(15)
  V_USER(73) = V(16)
      
END SUBROUTINE Shuffle_kpp2user

! End of Shuffle_kpp2user function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! GetMass - compute total mass of selected atoms
!   Arguments :
!      CL        - Concentration of all species (local)
!      Mass      - value of mass balance
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE GetMass ( CL, Mass )

! CL - Concentration of all species (local)
  REAL(kind=dp) :: CL(NSPEC)
! Mass - value of mass balance
  REAL(kind=dp) :: Mass(1)

      
END SUBROUTINE GetMass

! End of GetMass function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE cb05cl_ae5_Util

