name: CAMP

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the testing docker image
      run: docker build -f Dockerfile.camp -t partmc-test .
    - name: Run the tests in the docker container
      run: docker run -v shared-data:/build -t partmc-test bash -c 'cd /build; make test'
    - name: Generate and upload coverage report
      uses: ./.github/actions/codecov
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
