name: Images

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # https://github.com/marketplace/actions/checkout
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1 # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Login to DockerHub
        uses: docker/login-action@v1 # https://github.com/marketplace/actions/docker-login
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ######################################################################################################
      # partmc
      - name: Build and push compdyn/partmc
        uses: docker/build-push-action@v2 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          context: .
          platforms: linux/amd64
          push: true
          no-cache: true
          tags: compdyn/partmc:latest

      ######################################################################################################
      # partmc-camp
      - name: Build and push compdyn/partmc-camp
        uses: docker/build-push-action@v2 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          file: Dockerfile.camp
          context: .
          platforms: linux/amd64
          push: true
          no-cache: true
          tags: compdyn/partmc-camp:latest
