name: TChem

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the testing docker image
      run: docker build -f Dockerfile.tchem -t partmc-test .
    - name: Run the tests in the docker container
      run: docker run -t partmc-test bash -c 'export CTEST_PARALLEL_LEVEL=4; cd /build; make test'
