#!/usr/bin/env python

import numpy as np
import matplotlib
matplotlib.use("PDF")
import matplotlib.pyplot as plt
import config

ccn_array_ss1 = np.loadtxt("data/ccn_average_ss1.txt")
ccn_array_ss2 = np.loadtxt("data/ccn_average_ss2.txt")
ccn_array_ss3 = np.loadtxt("data/ccn_average_ss3.txt")

plt.clf()
plt.plot(ccn_array_ss1[:,0], 'b-', label = '10K flat')
plt.plot(ccn_array_ss1[:,1], 'g-', label = '10K -1')
plt.plot(ccn_array_ss1[:,2], 'r-', label = '10K -2')
plt.plot(ccn_array_ss1[:,3], 'b--', label = '10K -3')
plt.plot(ccn_array_ss1[:,4], 'g--', label = '10K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.001')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_ss4.pdf")

plt.clf()
plt.plot(ccn_array_ss2[:,0], 'b-', label = '10K flat')
plt.plot(ccn_array_ss2[:,1], 'g-', label = '10K -1')
plt.plot(ccn_array_ss2[:,2], 'r-', label = '10K -2')
plt.plot(ccn_array_ss2[:,3], 'b--', label = '10K -3')
plt.plot(ccn_array_ss2[:,4], 'g--', label = '10K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.01')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_ss5.pdf")

plt.clf()
plt.plot(ccn_array_ss3[:,0], 'b-', label = '10K flat')
plt.plot(ccn_array_ss3[:,1], 'g-', label = '10K -1')
plt.plot(ccn_array_ss3[:,2], 'r-', label = '10K -2')
plt.plot(ccn_array_ss3[:,3], 'b--', label = '10K -3')
plt.plot(ccn_array_ss3[:,4], 'g--', label = '10K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.03')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_ss6.pdf")

plt.clf()
plt.plot(ccn_array_ss1[:,5], 'b-', label = '100K flat')
plt.plot(ccn_array_ss1[:,6], 'g-', label = '100K -1')
plt.plot(ccn_array_ss1[:,7], 'r-', label = '100K -2')
plt.plot(ccn_array_ss1[:,8], 'b--', label = '100K -3')
plt.plot(ccn_array_ss1[:,9], 'g--', label = '100K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.001')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_100K_ss4.pdf")

plt.clf()
plt.plot(ccn_array_ss2[:,5], 'b-', label = '100K flat')
plt.plot(ccn_array_ss2[:,6], 'g-', label = '100K -1')
plt.plot(ccn_array_ss2[:,7], 'r-', label = '100K -2')
plt.plot(ccn_array_ss2[:,8], 'b--', label = '100K -3')
plt.plot(ccn_array_ss2[:,9], 'g--', label = '100K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.01')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_100K_ss5.pdf")

plt.clf()
plt.plot(ccn_array_ss3[:,5], 'b-', label = '100K flat')
plt.plot(ccn_array_ss3[:,6], 'g-', label = '100K -1')
plt.plot(ccn_array_ss3[:,7], 'r-', label = '100K -2')
plt.plot(ccn_array_ss3[:,8], 'b--', label = '100K -3')
plt.plot(ccn_array_ss3[:,9], 'g--', label = '100K -4')
#plt.axis([0, 24, 0, 1])
plt.legend(loc = 'upper right')
plt.xlabel("time (hours)")
plt.ylabel("ccn concentration (m^{-3})")
plt.title('S_c = 0.03')
fig = plt.gcf()
fig.savefig("figs/ccn_conc_100K_ss6.pdf")

